### ISSUE TITLE
Correções na gramática para linguagem formal.

### ISSUE THREAD

**Issue by johannareyy** [thalesms2/adsomos-docs#15]
Home
referente > referentes

Home/Padrão/Nome do arquivo
conteudo > conteúdo

Home/Padrão/Ao adicionar um arquivo novo
cria-lo > criá-lo
adiciona-lo > adicioná-lo

Markdown/Negrito
Tá em negrito > Está em negrito
Também tá em negrito > Também está em negrito

Markdown/Itálico
Tá em itálico > Está em itálico
Também tá em itálico > Também está em itálico

Markdown/Tabela
Alinhado a esquerda > Alinhado à esquerda
Alinhado a direita > Alinhado à direita

Procedimentos genéricos/Não se exclui cadastros
excluido > excluído
colocar um ponto no lugar da vírgula ''pode-se excluir. Caso fosse excluido...''

Gestor XXI/Comercial/Vendas/Erro de IE
informação incorreta > informações incorretas

Gestor XXI/Industrial/Tercerização
impossivel utiliza-lo > impossível utilizá-lo
fisico > físico

Gestor XXI/Consulta log
Utilitarios > Utilitários
Utilitarios > Utilitários        os dois estão sem acento

TNFe
inicia-lo > iniciá-lo

SmartNet
evidencias > evidências

Suporte/Movidesk/Telefonia
O cadastro server para adicionar > O cadastro serve para adicionar (?) 

Bando de dados/Tabelas/Tabelas do banco de dados
Executaveis > Executáveis
usuario > usuário

Bando de dados/Inserir tabela ATU001 backups recém atualizados
vem > vêm

Bando de dados/Backup
particulariedades > particularidades
a baixo > abaixo

**Comment by thalesms2** [comment]
Feito todas as alterações, exceto no arquivo "Consulta log"
Utilitários é um caminho no sistema no qual está sem acento, por esse motivo também foi optado deixar sem acento na documentação.

Commit: a3bfb300cdfbdd070b0720999347d5bfc0c58e79
